package com.jiang.employeeDao;

import com.jiang.mybatis.Dept;
import com.jiang.mybatis.DeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    int countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    Dept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dept
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    int updateByPrimaryKey(Dept record);
}