package com.jiang.mybatis;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dept.id
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dept.dept_name
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dept.id
     *
     * @return the value of tab_dept.id
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dept.id
     *
     * @param id the value for tab_dept.id
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dept.dept_name
     *
     * @return the value of tab_dept.dept_name
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dept.dept_name
     *
     * @param deptName the value for tab_dept.dept_name
     *
     * @mbggenerated Wed Jun 09 10:08:40 CST 2021
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}